# Generated by Django 4.2.1 on 2023-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('num_chekpoint', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogVisit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField()),
                ('status', models.BooleanField()),
                ('num_checkpoint', models.CharField()),
                ('permit_id', models.CharField(default=None)),
                ('time_detection', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOS',
            fields=[
                ('login', models.CharField(primary_key=True, serialize=False)),
                ('time_detection', models.DateTimeField(auto_now_add=True)),
                ('permit_id', models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.DateTimeField>')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
