# Generated by Django 4.2.1 on 2023-05-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useros',
            name='permit_id',
        ),
    ]
