# Generated by Django 4.2.1 on 2023-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_useros_permit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logvisit',
            name='permit_id',
        ),
        migrations.AlterField(
            model_name='logvisit',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
