# Generated by Django 4.2.1 on 2023-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_logvisit_permit_id_alter_logvisit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logvisit',
            name='permit_id',
            field=models.CharField(default=None),
        ),
    ]
