# Generated by Django 4.2.1 on 2023-05-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_logvisit_permit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logvisit',
            name='permit_id',
        ),
    ]
