# Generated by Django 4.2.1 on 2023-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_logvisit_permit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logvisit',
            name='permit_id',
            field=models.CharField(),
        ),
    ]
