# Generated by Django 4.2.1 on 2023-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_logvisit_num_checkpoint_alter_logvisit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logvisit',
            name='num_checkpoint',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='logvisit',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='logvisit',
            name='user',
            field=models.CharField(),
        ),
    ]
