# Generated by Django 4.2.1 on 2023-05-06 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_logvisit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='time_of_work_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 17, 13, 20, 336696)),
        ),
    ]
