# Generated by Django 4.2.1 on 2023-05-06 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_gate_time_of_work_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='time_of_work_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 17, 13, 58, 915043, tzinfo=datetime.timezone.utc)),
        ),
    ]
