# Generated by Django 4.2.1 on 2023-05-06 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_gate_time_of_work_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='time_of_work_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
